spring:
  application:
    name: metadata
  user:
    service:
      url: "http://localhost:8083"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/metadata
    username: postgres
    password: 12345

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
